### ISSUE TITLE
Maybe replace moment with a date-fns 

### ISSUE THREAD

**Issue by morajabi** [dinkbit/epoch#2]
Basically, it doesn't do much in terms of making project more usable, but it makes development easier maybe it can help with load time too. Feel free to close it.

**Comment by joecohens** [comment]
Hey! Thanks for the issue :) we started with date-fns (which I love) but the issue we have is that datetime component from ant design uses moment underneath to set and update dates, so unless we change the datetime component or the library it self we still need to use moment, I didn't what to use both.

**Comment by morajabi** [comment]
Makes total sense :) A👍 for starting with that at first! Although for such a small project it doesn't really matter and most importantly, product outcome matters not what's underneath.
