### ISSUE TITLE
Time Picker should at Start/End of day buttons

### ISSUE THREAD

**Issue by wesbos** [dinkbit/epoch#3]
Usually when I am picking an epoch I need the start or end of day. Right now that means scrolling the H/M/S to select the first or last items. Would be nice to have either a button to go to SOD or EOD, or in the display below, just show the timestamps for SOD and EOD. I do this pretty easily with datefns right now .startOf('day')

**Comment by joecohens** [comment]
Thank you for the recommendation! Done in https://github.com/dinkbit/epoch/pull/5
